import React, { useState } from 'react';
import {
  Code2,
  FileCode,
  ShieldCheck,
  Play,
  CheckCircle2,
  Copy,
  Sparkles,
  Terminal,
  Cpu,
  Layers,
  Wrench,
  AlertTriangle,
} from 'lucide-react';

interface Template {
  id: string;
  name: string;
  category: string;
  description: string;
  code: string;
}

export const SmartContractStudioView: React.FC = () => {
  const [activeTab, setActiveTab] = useState<'templates' | 'aiBuilder' | 'audit' | 'deployed'>('aiBuilder');
  const [aiPrompt, setAiPrompt] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [copiedCode, setCopiedCode] = useState(false);
  const [deployStatus, setDeployStatus] = useState<string | null>(null);

  const [contractCode, setContractCode] = useState<string>(`// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

contract CryptfestToken is ERC20, Ownable {
    constructor(uint256 initialSupply) ERC20("Cryptfest Governance", "FEST") Ownable(msg.sender) {
        _mint(msg.sender, initialSupply * 10 ** decimals());
    }

    function mint(address to, uint256 amount) public onlyOwner {
        _mint(to, amount);
    }
}`);

  const templates: Template[] = [
    {
      id: 'erc20',
      name: 'ERC-20 Fungible Token',
      category: 'Tokens',
      description: 'Standard mintable & burnable governance token template with OpenZeppelin security.',
      code: `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

contract CustomToken is ERC20, Ownable {
    constructor() ERC20("Custom Token", "CTK") Ownable(msg.sender) {
        _mint(msg.sender, 1000000 * 10 ** decimals());
    }
}`,
    },
    {
      id: 'erc721',
      name: 'ERC-721 NFT Collection',
      category: 'NFTs',
      description: 'NFT Smart Contract with max supply, whitelist proof, and royalty enforcement.',
      code: `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";

contract CustomNFT is ERC721 {
    uint256 public nextTokenId;
    constructor() ERC721("Custom Collection", "CNFT") {}

    function mint(address to) public {
        _safeMint(to, nextTokenId);
        nextTokenId++;
    }
}`,
    },
    {
      id: 'staking',
      name: 'DeFi Yield Staking Vault',
      category: 'DeFi',
      description: 'Time-locked reward distributor pool with dynamic APY distribution.',
      code: `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

contract StakingVault {
    mapping(address => uint256) public stakedBalance;
    function stake() external payable {
        stakedBalance[msg.sender] += msg.value;
    }
}`,
    },
    {
      id: 'dao',
      name: 'DAO Treasury & Governance',
      category: 'Governance',
      description: 'On-chain voting proposal manager with timelock execution mechanism.',
      code: `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

contract DAOGovernance {
    uint256 public proposalCount;
    struct Proposal { string desc; uint256 votes; }
    mapping(uint256 => Proposal) public proposals;
}`,
    },
  ];

  const handleGenerateAiContract = () => {
    if (!aiPrompt.trim()) return;
    setIsGenerating(true);
    setTimeout(() => {
      setContractCode(`// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title Generated by Cryptfest AI Contract Builder
 * @notice Prompt: ${aiPrompt}
 */
contract AI_Generated_Contract {
    address public owner;
    mapping(address => uint256) public balances;

    event GeneratedEvent(address indexed user, uint256 amount);

    constructor() {
        owner = msg.sender;
    }

    function executeLogic() external payable {
        require(msg.value > 0, "Invalid payload value");
        balances[msg.sender] += msg.value;
        emit GeneratedEvent(msg.sender, msg.value);
    }
}`);
      setIsGenerating(false);
    }, 1200);
  };

  const handleDeployContract = () => {
    setDeployStatus('Compiling Bytecode & Generating ABI...');
    setTimeout(() => {
      setDeployStatus('Broadcasting EIP-1559 Transaction to Ethereum Mainnet...');
      setTimeout(() => {
        setDeployStatus('SUCCESS! Deployed to 0x71F9...8A92 (Block #19842104)');
      }, 1500);
    }, 1200);
  };

  return (
    <div className="max-w-[1600px] mx-auto space-y-6 pb-12 w-full">
      {/* Top Banner */}
      <div className="bg-[#141419] border-2 border-white p-6 sm:p-8 shadow-[8px_8px_0px_0px_#ccff00] flex flex-col md:flex-row items-start md:items-center justify-between gap-6">
        <div>
          <span className="px-2.5 py-1 bg-[#ccff00] text-black text-[10px] font-black font-mono uppercase border border-black shadow-[2px_2px_0px_0px_#000]">
            EVM & SOLANA IDE
          </span>
          <h2 className="text-2xl font-black text-white font-mono uppercase tracking-tight mt-2">
            SMART CONTRACT STUDIO & AI COMPILER
          </h2>
          <p className="text-xs text-slate-300 font-mono mt-1">
            BUILD, AUDIT, TEST, DEPLOY, AND VERIFY ON-CHAIN PROTOCOLS WITH ZERO BOILERPLATE.
          </p>
        </div>

        {/* Tab switchers */}
        <div className="flex flex-wrap gap-2">
          {[
            { id: 'aiBuilder', label: 'AI BUILDER', icon: Sparkles },
            { id: 'templates', label: 'TEMPLATES', icon: Layers },
            { id: 'audit', label: 'SECURITY AUDIT', icon: ShieldCheck },
          ].map((tab) => {
            const Icon = tab.icon;
            return (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id as any)}
                className={`px-4 py-2 font-mono text-xs font-black uppercase border-2 shadow-[2px_2px_0px_0px_#000] flex items-center gap-2 cursor-pointer ${
                  activeTab === tab.id
                    ? 'bg-[#ccff00] text-black border-black'
                    : 'bg-[#0a0a0c] text-white border-white/40'
                }`}
              >
                <Icon className="w-4 h-4" /> {tab.label}
              </button>
            );
          })}
        </div>
      </div>

      {activeTab === 'aiBuilder' && (
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
          {/* Prompt & Controls Column (5 cols) */}
          <div className="lg:col-span-5 bg-[#141419] border-2 border-white p-6 shadow-[6px_6px_0px_0px_#00f0ff] space-y-5 flex flex-col justify-between">
            <div className="space-y-4">
              <h3 className="text-lg font-black text-white font-mono uppercase border-b-2 border-white pb-3 flex items-center gap-2">
                <Sparkles className="w-5 h-5 text-[#00f0ff]" /> PROMPT AI CONTRACT ENGINE
              </h3>

              <div>
                <label className="text-xs font-mono font-black text-slate-300 uppercase">
                  DESCRIBE YOUR SMART CONTRACT REQUIREMENTS:
                </label>
                <textarea
                  rows={5}
                  placeholder="e.g. Create a staking contract with 14-day lockup, 15% APY rewards in FEST token, emergency withdrawal mechanism, and reentrancy guard."
                  value={aiPrompt}
                  onChange={(e) => setAiPrompt(e.target.value)}
                  className="w-full mt-2 bg-[#0a0a0c] border-2 border-white p-3 text-xs font-mono text-white focus:outline-none"
                />
              </div>

              <button
                onClick={handleGenerateAiContract}
                disabled={isGenerating}
                className="w-full py-3 bg-[#00f0ff] text-black font-mono font-black text-xs uppercase border-2 border-black shadow-[4px_4px_0px_0px_#000] hover:bg-[#33f3ff] cursor-pointer flex items-center justify-center gap-2"
              >
                <Cpu className="w-4 h-4" /> {isGenerating ? 'GENERATING SOLIDITY...' : 'GENERATE CONTRACT CODE'}
              </button>

              {/* Preset Prompts */}
              <div className="space-y-2 pt-2">
                <span className="text-[10px] font-mono font-black text-slate-400 uppercase">SUGGESTED CONTRACT SPECS:</span>
                <div className="flex flex-wrap gap-2">
                  {[
                    'ERC-20 Token with 1% Tax to Marketing',
                    'NFT Vesting Vault with Linear Unlocking',
                    'Escrow Contract with Multi-Sig Arbitration',
                  ].map((preset, idx) => (
                    <button
                      key={idx}
                      onClick={() => setAiPrompt(preset)}
                      className="px-2.5 py-1 bg-[#0a0a0c] border border-white text-[10px] font-mono text-slate-300 uppercase hover:text-[#ccff00] cursor-pointer"
                    >
                      {preset}
                    </button>
                  ))}
                </div>
              </div>
            </div>

            {/* Quick Deploy Box */}
            <div className="p-4 bg-[#0a0a0c] border-2 border-white space-y-3 shadow-[3px_3px_0px_0px_#ff007f]">
              <h4 className="text-xs font-mono font-black text-white uppercase">ONE-CLICK COMPILER & DEPLOYER</h4>
              <button
                onClick={handleDeployContract}
                className="w-full py-3 bg-[#ccff00] text-black font-mono font-black text-xs uppercase border-2 border-black shadow-[3px_3px_0px_0px_#000] hover:bg-[#d8ff33] cursor-pointer flex items-center justify-center gap-2"
              >
                <Play className="w-4 h-4 fill-black" /> DEPLOY TO MAINNET
              </button>

              {deployStatus && (
                <div className="p-2.5 bg-[#141419] border border-white text-[11px] font-mono font-black text-[#ccff00]">
                  {deployStatus}
                </div>
              )}
            </div>
          </div>

          {/* Code Editor Column (7 cols) */}
          <div className="lg:col-span-7 bg-[#141419] border-2 border-white p-6 shadow-[6px_6px_0px_0px_#ff007f] space-y-4 flex flex-col">
            <div className="flex items-center justify-between border-b-2 border-white pb-3">
              <div className="flex items-center gap-2">
                <FileCode className="w-5 h-5 text-[#ff007f]" />
                <span className="font-mono font-black text-sm text-white uppercase">CryptfestToken.sol</span>
              </div>
              <button
                onClick={() => {
                  navigator.clipboard.writeText(contractCode);
                  setCopiedCode(true);
                  setTimeout(() => setCopiedCode(false), 2000);
                }}
                className="px-3 py-1 bg-[#0a0a0c] border border-white text-xs font-mono text-white flex items-center gap-1.5 cursor-pointer hover:bg-[#202028]"
              >
                <Copy className="w-3.5 h-3.5" /> {copiedCode ? 'COPIED' : 'COPY'}
              </button>
            </div>

            <textarea
              rows={18}
              value={contractCode}
              onChange={(e) => setContractCode(e.target.value)}
              className="w-full bg-[#0a0a0c] border-2 border-white p-4 font-mono text-xs text-[#ccff00] focus:outline-none leading-relaxed resize-none shadow-[inner_0_0_10px_rgba(0,0,0,0.8)]"
            />
          </div>
        </div>
      )}

      {activeTab === 'templates' && (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {templates.map((tmpl) => (
            <div
              key={tmpl.id}
              className="bg-[#141419] border-2 border-white p-6 shadow-[6px_6px_0px_0px_#ccff00] space-y-4 flex flex-col justify-between"
            >
              <div>
                <span className="px-2 py-0.5 bg-[#ff007f] text-white text-[10px] font-mono font-black uppercase border border-black shadow-[2px_2px_0px_0px_#000]">
                  {tmpl.category}
                </span>
                <h3 className="text-xl font-black text-white font-mono uppercase mt-2">{tmpl.name}</h3>
                <p className="text-xs text-slate-300 font-mono mt-1">{tmpl.description}</p>

                <div className="mt-4 p-3 bg-[#0a0a0c] border border-white font-mono text-[11px] text-slate-300 max-h-36 overflow-y-auto no-scrollbar">
                  <pre>{tmpl.code}</pre>
                </div>
              </div>

              <button
                onClick={() => {
                  setContractCode(tmpl.code);
                  setActiveTab('aiBuilder');
                }}
                className="w-full py-2.5 bg-[#ccff00] text-black font-mono font-black text-xs uppercase border-2 border-black shadow-[3px_3px_0px_0px_#000] cursor-pointer hover:bg-[#d8ff33]"
              >
                LOAD INTO EDITOR
              </button>
            </div>
          ))}
        </div>
      )}

      {activeTab === 'audit' && (
        <div className="bg-[#141419] border-2 border-white p-6 sm:p-8 shadow-[8px_8px_0px_0px_#00f0ff] space-y-6">
          <div className="flex items-center gap-3 border-b-2 border-white pb-4">
            <ShieldCheck className="w-7 h-7 text-[#00f0ff]" />
            <div>
              <h3 className="text-xl font-black text-white font-mono uppercase">AI STATIC ANALYSIS & VULNERABILITY REPORT</h3>
              <p className="text-xs text-slate-300 font-mono">AUTOMATED REENTRANCY, OVERFLOW, AND PRIVILEGE AUDITING</p>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 font-mono text-xs">
            <div className="p-4 bg-[#0a0a0c] border-2 border-white shadow-[3px_3px_0px_0px_#ccff00]">
              <div className="text-slate-400">SECURITY SCORE</div>
              <div className="text-3xl font-black text-[#ccff00] mt-1">98 / 100</div>
              <div className="text-[10px] text-emerald-400 mt-1">✓ PASSED OPCODES AUDIT</div>
            </div>

            <div className="p-4 bg-[#0a0a0c] border-2 border-white shadow-[3px_3px_0px_0px_#00f0ff]">
              <div className="text-slate-400">REENTRANCY VULNERABILITY</div>
              <div className="text-xl font-black text-[#00f0ff] mt-1">NONE DETECTED</div>
              <div className="text-[10px] text-slate-300 mt-1">CEI PATTERN COMPLIANT</div>
            </div>

            <div className="p-4 bg-[#0a0a0c] border-2 border-white shadow-[3px_3px_0px_0px_#ff007f]">
              <div className="text-slate-400">GAS EFFICIENCY TIER</div>
              <div className="text-xl font-black text-[#ff007f] mt-1">OPTIMAL (94%)</div>
              <div className="text-[10px] text-slate-300 mt-1">UNCHECKED INCR USED</div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
